version: '3'
services:
  app:
    container_name: issue-tracker
    restart: always
    build: .
    ports:
      - "80:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      - PORT=8080
      - HOST=db
      - PASSWORD=Wux70bah!
      - USER=root
      - DATABASE=issue_tracker
  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - 3306:3306
